#!/bin/bash

function runserver {
source ./env/bin/activate
./manage.py syncdb
./manage.py schemamigration ucapp --auto
./manage.py schemamigration li_registration --auto
./manage.py schemamigration static_precompiler --auto
./manage.py migrate ucapp
./manage.py migrate li_registration
./manage.py migrate static_precompiler
}

runserver