#!/bin/bash

function runserver {
    source ./env/bin/activate
    echo "yes" | python manage.py collectstatic
    python manage.py validate
    python manage.py syncdb
    python manage.py evolve --hint
    python manage.py evolve --hint --execute
    
    python manage.py runserver
}

runserver
