#!/bin/bash

function runserver {
    source ./env/bin/activate
    #windows version below
    source ./env/Scripts/activate
    echo "yes" | python manage.py collectstatic
    python manage.py validate
    python manage.py syncdb
    #python manage.py migrate
    python manage.py update_index

    #python manage.py evolve --hint
    #python manage.py evolve --hint --execute
    
    python manage.py runserver
}

runserver
